const { initializeApp, cert } = require('firebase-admin/app');
const { getFirestore } = require('firebase-admin/firestore');
const serviceAccount = require('../service-account.json');

initializeApp({ credential: cert(serviceAccount) });
const db = getFirestore();

const descriptions = {
    "Abracadabra NYC": "Step into a world of wonder with Abracadabra NYC, the ultimate destination for costumes, magic, and makeup! Whether you're preparing for a theatrical masterpiece or looking for the perfect Halloween disguise, their vast selection and expert staff ensure you'll find exactly what you need to transform your imagination into reality.",
    "Acronis International GmbH": "Secure your digital life with Acronis, the global leader in cyber protection. Combining reliable data backup with advanced cybersecurity, Acronis provides a unified approach to safety, ensuring your personal and business data remains private, accessible, and secure against modern threats.",
    "AGMES": "Discover the sculptural elegance of AGMES, a jewelry brand that celebrates modern art and sustainable craftsmanship. Each piece is thoughtfully designed and handmade in New York, offering a timeless aesthetic that complements the wearer's individuality with grace and sophistication.",
    "Albee Baby": "Welcome to parenthood with Albee Baby, your trusted partner for premium baby gear. From strollers and car seats to nursery furniture, Albee Baby curates a selection of top-rated products to ensure safety, comfort, and style for your little one's earliest adventures.",
    "ALLDATAdiy.com": "Empower your inner mechanic with ALLDATAdiy.com, the leading provider of OEM automotive repair information. Get instant access to diagnostic charts, wiring diagrams, and step-by-step repair manuals, giving you the confidence to maintain and repair your vehicle like a pro.",
    "Altium": "Innovate without boundaries using Altium, the world's most trusted PCB design software. Engineered for performance and collaboration, Altium connects designers and engineers, streamlining the journey from concept to manufacturing for cutting-edge electronic products.",
    "Amana": "Experience the reliability of Amana, a brand synonymous with quality American craftsmanship. From heating and cooling systems to dependable kitchen appliances, Amana delivers simple, smart solutions designed to keep your home comfortable and running smoothly.",
    "Amazfit US": "Elevate your fitness journey with Amazfit, where smart technology meets stylish design. Their comprehensive range of wearables tracks your health, sleep, and performance metrics, empowering you to lead a more active, balanced, and informed lifestyle.",
    "American National Standards Institute Inc.": "Drive innovation and quality with the American National Standards Institute (ANSI). As the voice of the U.S. standards and conformity assessment system, ANSI provides the critical frameworks that enhance global competitiveness and ensure the safety and reliability of products and services.",
    "AmWager": "Get in the game with AmWager, the most advanced online horse racing wagering platform. Featuring real-time data, powerful handicapping tools, and seamless streaming, AmWager offers an optimized betting experience for enthusiasts who demand speed and precision.",
    "Annmarie Skin Care": "Reveal your natural radiance with Annmarie Skin Care, a line dedicated to honest, wildcrafted, and organic beauty. Infused with potent botanicals and crafted with intention, their products nourish your skin while respecting the planet, delivering a glow that is truly transformative.",
    "antonline": "Gear up with antonline, your premier source for the latest in gaming and consumer electronics. With a vast inventory of consoles, components, and accessories from top brands, antonline delivers the cutting-edge technology you need to stay ahead of the curve.",
    "Aroma360": "Transform your environment with Aroma360, the pioneer in scent marketing and luxury home fragrancing. their innovative cold-air diffusion technology and exquisite scent collections create immersive atmospheres that stick with you, elevating any space into a sensory sanctuary.",
    "AudiobooksNow": "Immerse yourself in a good story with AudiobooksNow, where your next great listen is just a click away. offering a flexible reliable service and a massive library of titles, they make it easy and affordable to enjoy bestsellers, classics, and new releases wherever you go.",
    "Awin (USD)": "Partner with Awin, a global affiliate marketing network that empowers businesses to grow. Connecting advertisers with a diverse network of publishers, Awin drives performance and innovation, creating meaningful partnerships that deliver tangible results.",
    "BannerBuzz": "Make a big impression with BannerBuzz, your go-to for custom signage and marketing materials. From vinyl banners to trade show displays, their high-quality printing and rapid turnaround times help your brand stand out and get noticed in any setting.",
    "Batteries Plus": "Power up your life with Batteries Plus, the nation's largest and fastest-growing battery, light bulb, and smartphone repair franchise. With expert advice and an unmatched selection, they are your one-stop solution for keeping all your essential devices running smoothly.",
    "Bc Babycare": "Nurture your little one with Bc Babycare, dedicated to designing innovative and safe products for modern families. combining functionality with gentle aesthetics, their range of baby essentials ensures comfort for your child and peace of mind for you.",
    "Beauty Care Choices": "Celebrate your unique style with Beauty Care Choices, a salon-professional retailer offering over 500 brands. With a team of licensed cosmetologists ready to assist, they provide personalized recommendations to help you find the perfect hair, skin, and nail products.",
    "Bellame": "Shatter the status quo with Bellame, a beauty brand that merges luxury skincare with empowering opportunity. Their science-backed, clinical-grade formulations deliver visible results, while their community-driven model inspires confidence and success.",
    "BestOfSigns": "Showcase your message with BestOfSigns, the leader in high-quality, affordable custom signage. offering a user-friendly design tool and a wide array of materials, they make it effortless to create professional banners, flags, and signs that capture attention.",
    "Beverly Diamonds": "Sparkle with elegance from Beverly Diamonds, a premier online jeweler known for exquisite craftsmanship. specializing in diamond engagement rings and fine jewelry, they offer stunning designs and exceptional value, making your special moments truly unforgettable.",
    "Bissell": "Clean with confidence using Bissell, a family-owned leader in homecare solutions for over 140 years. From pet hair erasers to deep cleaners, Bissell's innovative products make it easy to maintain a spotless home, so you can spend more time making messes and memories.",
    "BlindsExpress.com": "Frame your view with BlindsExpress.com, your destination for premium window treatments at unbeatable prices. With a huge selection of blinds, shades, and shutters from top brands, they make it simple to find the perfect custom fit for your home's style.",
    "Bliss World": "Find your happy place with Bliss World, the spa-powered skincare brand that brings the facial to your bathroom. Famous for their fun, effective, and no-nonsense formulas, Bliss delivers glowing, healthy skin with products that feel as good as they look.",
    "Canadapetcare": "Care for your furry friends with Canadapetcare, a trusted supplier of affordable pet health products. dedicated to making pet care accessible, they provide genuine treatments for fleas, ticks, and more, ensuring your pets stay happy and healthy without breaking the bank.",
    "CPO Power Tools": "Build your dreams with CPO Power Tools, the industry leader in new and reconditioned tools. Partnering with top brands, CPO offers an extensive selection of reliable, high-performance equipment at significant savings, favored by professionals and DIYers alike.",
    "Crutchfield.com": "Experience audio and video like never before with Crutchfield, the electronics retailer famous for its legendary support. Since 1974, their experts have helped customers choose and install the perfect gear, creating personalized entertainment systems that truly rock.",
    "Cupshe APAC": "Dive into confidence with Cupshe, the swimwear brand inspired by the California lifestyle. known for their vibrant prints and flattering cuts, Cupshe offers accessible, stylish swimwear that celebrates every body, making every beach day a fashion statement.",
    "David's Bridal": "Walk down the aisle in style with David's Bridal, the ultimate authority on wedding attire. With an inclusive range of sizes and styles for brides and bridesmaids, they make it magical and affordable to find the dress of your dreams for your big day.",
    "Dollar Rent-a-Car, Inc.": "Hit the road for less with Dollar Rent A Car, the smart choice for family vacations and business travel. Known for their transparent pricing and reliable fleet, Dollar helps you save on your journey so you can spend more on your destination.",
    "Donald Pliner": "Step into luxury with Donald Pliner, a footwear brand renowned for its impeccable craftsmanship and comfort. Blending innovative materials with modern design, their shoes make a bold statement, offering sophisticated style for those who value distinctiveness.",
    "DRIFTAWAY": "Wake up to adventure with DRIFTAWAY, a personalized coffee subscription that explores the world of single-origin beans. Connecting you directly to the farmers, they deliver freshly roasted coffee matched to your taste, turning your morning ritual into a journey of discovery.",
    "Eden": "Nourish your spirit with Eden, the premier online Christian store. Offering a vast selection of books, bibles, music, and gifts, Eden serves as a resource for inspiration and growth, helping you deepen your faith and share it with others.",
    "EFE": "See the world clearly with EFE, a pioneer in the eyewear industry committed to quality and affordability. combining trendy designs with precision optics, EFE ensures that stylish, high-quality glasses are accessible to everyone, framing your face with confidence.",
    "Electric City Roasting Coffee": "Energize your day with Electric City Roasting, where sustainability meets superior taste. Passionate about ethical sourcing and artisanal roasting, they deliver exceptional coffee that empowers farmers and delights your palate with every sip.",
    "Exposed SkinCare": "Reclaim your confidence with Exposed SkinCare, the complete acne solution that combines science and nature. Their synergistic system targets acne at the source while soothing the skin, delivering clear, healthy results without the irritation of harsh chemicals.",
    "FineJewelers.com": "Celebrate life's moments with FineJewelers.com, your online source for quality gemstones and metals. With a commitment to American craftsmanship and ethical sourcing, they offer a stunning array of rings, necklaces, and earrings to cherish forever.",
    "FineStationery": "Make your mark with FineStationery, the definitive source for personalized paper goods. From elegant wedding invitations to custom business cards, their curated selection of designer brands helps you communicate with style, grace, and a personal touch.",
    "Flower.com Flowers": "Brighten someone's day with Flower.com, the easy way to send fresh, beautiful blooms. With a network of expert florists, they ensure your floral gifts are hand-arranged and delivered with care, perfectly expressing your sentiments for any occasion.",
    "FlowerShopping.com": "Deliver a smile with FlowerShopping.com, your reliable partner for floral gifting. Offering a wide variety of fresh flowers, plants, and gift baskets, they make it simple and affordable to share love, sympathy, and celebration across the miles.",
    "Fox Rent a Car": "Drive a better deal with Fox Rent A Car, the value leader in airport car rentals. offering a diverse fleet of modern vehicles at competitive rates, Fox provides a friendly, efficient rental experience that gets you on the road to your next adventure.",
    "Fresh Meal Plan": "Fuel your fitness with Fresh Meal Plan, the meal delivery service designed for active lifestyles. eliminating the hassle of prep and cooking, they deliver chef-prepared, nutrient-packed meals right to your door, helping you eat clean and stay lean.",
    "FyreLux": "Ignite your style with FyreLux, the premier destination for luxury lighters and accessories. Blending sophisticated design with rugged functionality, FyreLux offers a curated collection for the modern enthusiast who appreciates quality, reliability, and a spark of elegance.",
    "GAT Sport": "Push your limits with GAT Sport, the trusted name in hardcore sports nutrition. scientifically engineered to maximize performance, their supplements help athletes worldwide build muscle, burn fat, and achieve their peak physical potential.",
    "GeekBuying.com": "Unleash your inner geek with GeekBuying.com, a global hub for the coolest tech gadgets. From smart home devices to the latest drones and wearables, they offer cutting-edge technology at unbeatable prices, satisfying tech lovers everywhere.",
    "Gem and Harmony": "Find your perfect match at Gem and Harmony, where fine jewelry meets incredible value. With a wide selection of diamonds, gemstones, and precious metals, they make it easy to find the perfect gift or a special treat that sparkles with quality and beauty.",
    "Grand Slam New York": "Wear your NY pride with Grand Slam New York, the ultimate fan shop for New York sports and souvenirs. From Yankees jerseys to NYPD apparel, they offer an authentic slice of the Big Apple, perfect for fans and tourists alike.",
    "Green Motion": "Travel responsibly with Green Motion, the world's leading eco-friendly car rental company. committed to reducing the environmental impact of travel, they offer a fleet of low-CO2 vehicles, allowing you to explore the world while protecting it.",
    "Haggar.com": "Dress with confidence in Haggar, the brand that invented the concept of slacks. Known for innovation, comfort, and durability, Haggar offers a wide range of men's apparel that looks sharp and feels great, from the office to the weekend.",
    "Halo Sleep": "Sleep soundly with Halo Sleep, the brand that revolutionized safe sleep for babies. Their original SleepSack and innovative bassinets are designed with your baby's safety and comfort in mind, helping the whole family get a better night's rest.",
    "HDIS": "Live life without limits with HDIS, the compassionate provider of incontinence supplies. offering personalized service and discreet delivery, HDIS helps you find the right products for your needs, restoring dignity and confidence to your daily life.",
    "Heat Holders": "Stay toasty with Heat Holders, creators of the world's warmest thermal socks. their advanced insulating yarn and brushing process trap heat closer to your skin, providing unbeatable warmth and comfort during the coldest winter days.",
    "Herbspro": "Embrace wellness with Herbspro, a leading online retailer of vitamins, herbs, and natural supplements. With thousands of products from top brands, they make it easy and affordable to support your holistic health journey with nature's best remedies.",
    "Highwood USA": "Relax in style with Highwood USA, makers of premium, ultra-low maintenance outdoor furniture. Crafted to look like real wood but built to withstand the elements, their eco-friendly pieces offer timeless beauty and durability for your outdoor sanctuary.",
    "Hotel Collection": "Bring the five-star experience home with Hotel Collection. specializing in luxury scents and premium bedding, they allow you to recreate the ambiance and comfort of top-tier hotels, transforming your living space into a daily getaway.",
    "Ishow Hair": "Express yourself with Ishow Hair, a top provider of high-quality human hair wigs and extensions. dedicated to beauty and versatility, Ishow offers a range of textures and styles that empower you to switch up your look instantly and flawlessly.",
    "iVisa": "Travel made simple with iVisa, your digital passport to the world. replacing bureaucratic headaches with a streamlined online process, iVisa processes travel visas and health declarations quickly and reliably, so you can focus on planning your trip, not paperwork.",
    "IWA Wine": "Celebrate the vine with IWA Wine, your expert source for wine cellars, racks, and accessories. passionate about the wine lifestyle, they offer everything you need to store, serve, and savor your collection, enhancing every glass you pour.",
    "Janet Howard": "Discover chic sophistication with Janet Howard, a boutique destination for curated fashion and accessories. blending timeless style with modern trends, Janet Howard offers pieces that help you express your unique personality and flair.",
    "JIMMYJANE": "Explore pleasure with JIMMYJANE, a design-centric brand revolutionizing intimate wellness. combining award-winning aesthetics with body-safe materials, their innovative products invite you to discover new sensations and embrace your sexuality with confidence.",
    "Kenneth Jay Lane": "Adorn yourself in fantasy with Kenneth Jay Lane, the king of costume jewelry. Beloved by fashion icons for decades, his innovative and glamorous designs allow every woman to make a bold, stylish statement without the high-jewelry price tag.",
    "KitchenAid Major Appliances": "Create culinary masterpieces with KitchenAid, the brand that fuels your passion for making. From their iconic mixers to state-of-the-art major appliances, KitchenAid combines professional performance with iconic design, inspiring you to cook, bake, and create.",
    "Koio": "Step up your sneaker game with Koio, the brand redefining luxury footwear. hand-crafted in Italy using the finest leathers, Koio sneakers offer the perfect blend of high-end quality, comfort, and minimalist design for the modern urbanite.",
    "Kole Imports": "Discover wholesale value with Kole Imports, one of the nation's largest direct importers of general merchandise. Serving retailers and non-profits, they offer an incredible variety of products at closeout prices, driving profit and value for businesses everywhere.",
    "Lifeline Skincare": "Regenerate your youth with Lifeline Skincare, the only skincare based on non-embryonic human stem cell extracts. their advanced formulas work at the cellular level to repair and rejuvenate, delivering firmer, smoother, and more youthful-looking skin.",
    "LOTFLY US": "Elevate your lifestyle with LOTFLY, a curator of unique and innovative consumer goods. From home essentials to personal care, LOTFLY brings you high-quality products designed to enhance your daily routine with style and functionality.",
    "Luzern Labs": "Experience the purity of Swiss beauty with Luzern Labs. combining organic Alpine extracts with advanced cosmeceuticals, their clean, cold-processed formulas deliver powerful anti-aging results while respecting the most sensitive skin.",
    "Lynnee": "Shine bright with Lynnee, your destination for trendy and affordable jewelry. whether you're looking for everyday sparkle or a statement piece for a night out, Lynnee offers designs that capture the latest fashion trends at a price you'll love.",
    "Malin+Goetz": "Simplify your regimen with Malin+Goetz, the modern apothecary for sensitive skin. balancing natural ingredients with advanced technology, their uncomplicated, gender-neutral products are designed to be gentle, effective, and efficient for all skin types.",
    "Maytag": "Depend on Maytag, the brand built on strength and durability. Known for their powerful performance and American heritage, Maytag appliances are engineered to handle your toughest loads and biggest messes, day in and day out.",
    "Mignon Faget": "Wear a piece of art with Mignon Faget, the New Orleans jewelry brand inspired by natural and architectural forms. Each collection tells a story, blending sterling silver and gold into timeless designs that capture the unique spirit and culture of the South.",
    "Ming Wang Knits": "Embrace effortless elegance with Ming Wang Knits, designed for the real lives of modern women. specializing in luxurious, wrinkle-resistant knits, their sophisticated pieces offer comfort, durability, and a perfect fit that moves with you from day to night.",
    "Misook": "Define your style with Misook, the pioneer of sophisticated knitwear. Known for impeccable tailoring that never wrinkles or fades, Misook offers timeless, polished wardrobe essentials that empower women to look and feel their best in any setting.",
    "Moerie Beauty": "Unlock your hair's potential with Moerie Beauty, the natural hair growth system. enriched with minerals and vitamins, their mineral-rich formulas stimulate follicles and strengthen strands, helping you achieve thicker, fuller, and healthier hair.",
    "Mojo Socks": "Energize your step with Mojo Socks, the leaders in compression hosiery. Combining medical-grade compression with cool, funky designs, Mojo Socks boost circulation and recovery, keeping your legs feeling fresh and looking great all day long.",
    "Mott & Bow": "Experience denim done right with Mott & Bow. By sourcing the finest denim fabrics and bypassing the middlemen, they deliver premium, handcrafted jeans that offer the perfect fit and comfort at a fair price, elevating your everyday uniform.",
    "mSpy": "Protect your loved ones with mSpy, the leading parental control and monitoring solution. providing real-time insights into digital activity, mSpy empowers parents to safeguard their children from online threats, ensuring peace of mind in a connected world.",
    "MTD Parts": "Keep your equipment running with MTD Parts, the original equipment parts manufacturer for outdoor power equipment. From blades to belts, they provide the exact replacement parts you need to maintain the performance and longevity of your machines.",
    "My Sensual Secrets": "Embrace your allure with My Sensual Secrets, a boutique for intimate apparel and wellness. offering a curated selection of lingerie and pleasure products, they encourage self-love and confidence, helping you explore and celebrate your sensuality.",
    "NAPA": "Get the good stuff at NAPA Auto Parts, your trusted source for automotive expertise. With a massive inventory of quality parts and tools, plus knowledgeable staff, NAPA keeps your vehicle running strong, whether you're a professional mechanic or a DIY enthusiast.",
    "No! Jeans": "Say yes to comfort with No! Jeans, the denim brand that defies convention. prioritizing fit and freedom of movement, No! Jeans creates stylish, comfortable denim that adapts to your lifestyle, proving that you don't have to sacrifice comfort for style.",
    "Oedro": "Upgrade your ride with OEDRO, a premier manufacturer of high-quality auto parts and accessories. famous for their floor mats and bumpers, OEDRO combines rugged durability with precise fitment, protecting and enhancing your vehicle for the road ahead.",
    "Oxygen Clothing": "Breathe new life into your wardrobe with Oxygen Clothing, the UK's destination for designer streetwear. Curating the best from iconic labels and emerging brands, they offer a fresh, trend-setting selection for the fashion-forward individual.",
    "Palm Beach Perfumes": "Indulge in luxury with Palm Beach Perfumes, your online boutique for authentic designer fragrances. Offering a vast collection of rare and classic scents at discounted prices, they make it affordable to find your signature scent.",
    "PandaHall": "Create something beautiful with PandaHall, the global market for beads and jewelry making supplies. With an enormous selection of materials and tools, PandaHall is a paradise for crafters and designers looking to bring their unique jewelry ideas to life.",
    "PartnerBoost": "Accelerate your growth with PartnerBoost, the innovative partnership management platform. bringing transparency and efficiency to affiliate marketing, PartnerBoost connects brands with top-tier partners, streamlining collaboration and maximizing revenue.",
    "Percival Menswear": "Redefine your look with Percival Menswear, the British brand subverting the classics. known for their unique textures, embroidery, and understated wit, Percival offers versatile, high-quality staples that add a distinct character to any man's wardrobe.",
    "Photobook Worldwide Sdn Bhd (AU & NZ)": "Capture your memories with Photobook Worldwide, the leading provider of personalized photo products. transforming your digital photos into handcrafted albums and gifts, they help you preserve your most cherished moments in stunning, tangible quality.",
    "Piscifun": "Fish with the family with Piscifun, dedicated to making fishing affordable and fun. designing high-performance reels, rods, and gear without the high price tag, Piscifun ensures that anglers of all levels can enjoy the thrill of the catch.",
    "Plae.co": "Let them play with PLAE, the kids' shoe brand built for active imaginations. combining customizable style with washable, durable materials and podiatrist-approved construction, PLAE shoes support healthy foot development while keeping up with every adventure.",
    "Purlisse": "Celebrate your beauty with Purlisse, where Asian wisdom meets modern philosophy. creating high-performance skincare that is gentle and effective, Purlisse helps you achieve a healthy, glowing complexion, proving that beautiful skin is the best foundation.",
    "PURTY BODY Affiliate Program": "Pamper yourself with PURTY BODY, a brand dedicated to wholesome, natural body care. crafting products with simple, effective ingredients, PURTY BODY nourishes your skin and senses, turning your daily routine into a ritual of self-care.",
    "Puzzle Master": "Challenge your mind with Puzzle Master, the ultimate source for brain teasers and puzzles. featuring an unmatched collection of wire, wood, and logic puzzles from around the world, they offer endless entertainment for solvers of all ages and skill levels.",
    "RAEN": "Look clearly through RAEN, the eyewear brand inspired by the West Coast sun. creating handmade, optical-quality frames with a modern classic aesthetic, RAEN offers authentic style that feels as good as it looks, capturing the free-spirited California lifestyle.",
    "Rakuten Advertising Welcome Program": "Join the Rakuten Advertising Welcome Program and step into a world of affiliate opportunity. As a global leader in performance marketing, Rakuten connects you with top brands and innovative tools, empowering you to monetize your content and grow your business.",
    "Rakuten Kobo Brazil": "Open up a world of reading with Rakuten Kobo, your digital bookshelf for eBooks and audiobooks. offering millions of titles and state-of-the-art eReaders, Kobo lets you carry your entire library with you, making reading accessible anytime, anywhere.",
    "Rakuten Marketing UK": "Drive performance with Rakuten Marketing UK, the industry-voted #1 affiliate network. leveraging data-driven insights and advanced technology, they bridge the gap between brands and their audiences, delivering campaigns that truly convert.",
    "Rent Cars": "Explore the globe with Rentcars, one of the world's largest online car rental platforms. comparing prices from hundreds of rental companies worldwide, Rentcars makes it easy to find the perfect vehicle at the best price for your next journey.",
    "Rexing": "Drive with confidence using Rexing, the trusted name in dash cams and automotive electronics. innovative and reliable, Rexing's advanced cameras capture every moment on the road, providing security, evidence, and peace of mind for every driver.",
    "Rover": "Treat your pet like family with Rover, the world's largest network of 5-star pet sitters and dog walkers. connecting pet parents with trusted care, Rover ensures your furry friend gets the love and attention they deserve when you can't be there.",
    "Royal Apparel": "Choose quality with Royal Apparel, the industry leader in premium, eco-friendly clothing manufacturing. Proudly made in the USA, they offer a wide range of sustainable basics and fashion-forward styles, proving that ethical production never goes out of style.",
    "Safeshell VPN": "Surf securely with Safeshell VPN, your shield for digital privacy. offering high-speed connections and robust encryption, Safeshell allows you to browse the internet freely and anonymously, protecting your data from prying eyes wherever you connect.",
    "SelectATicket.com": "Get the best seats with SelectATicket.com, your ticket to the hottest events. serving fans for over 40 years, they offer a secure marketplace for sports, concerts, and theater tickets, ensuring you never miss out on the live experiences you love.",
    "Seven7 Jeans": "Flaunt your fit with Seven7 Jeans, the denim brand that celebrates curves. known for their innovative stretch fabrics and body-enhancing cuts, Seven7 creates stylish, comfortable jeans that fit and flatter every figure perfectly.",
    "Sharper Image": "Discover the future with Sharper Image, the iconic retailer of innovative gadgets and gifts. from high-tech massage chairs to cutting-edge electronics, Sharper Image offers unique products that add fun, comfort, and convenience to your life.",
    "Simone I. Smith": "Shine with strength with Simone I. Smith Jewelry. bold, beautiful, and empowering, this collection blends classic hoop designs with modern touches, celebrating the resilience and style of women everywhere while supporting causes close to the heart.",
    "Simply Wholesale": "Save big with Simply Wholesale, Australia's favorite online department store. offering a massive range of products from electronics to homewares at factory-direct prices, Simply Wholesale makes it easy to find everything you need for less.",
    "Sleep & Beyond": "Experience organic comfort with Sleep & Beyond, the leader in natural wool bedding. crafting hypoallergenic comforters, pillows, and sheets, they provide a pure, chemical-free sleep environment that rejuvenates your body and mind naturally.",
    "Splits59.com": "Move with purpose in Splits59, the activewear brand for the modern woman. fusing high-performance fabrics with sleek, retro-inspired designs, Splits59 creates workout gear that looks chic in the studio and effortless on the street.",
    "SpyAssociates.com": "Equip yourself with SpyAssociates.com, the premier supplier of surveillance and security gear. From hidden cameras to GPS trackers, they provide professional-grade technology to protect your business, family, and assets with discretion and reliability.",
    "Stylevana": "Unlock your beauty potential with Stylevana, the ultimate destination for Asian fashion and beauty. discovering the trendiest skincare and makeup from Korea, Japan, and Taiwan, Stylevana helps you explore new routines and find your perfect glow.",
    "TAGS": "Express your vibe with TAGS, the boutique destination for contemporary luxury fashion. Curating the hottest styles from LA's most coveted designers, TAGS offers a shopping experience that is always on-trend, effortless, and undeniably cool.",
    "The Bouqs": "Send kindness with The Bouqs Co., delivering farm-fresh flowers from sustainable eco-friendly farms. cutting out the middleman, they ensure longer-lasting blooms and support farmers, making every bouquet a beautiful gesture for people and the planet.",
    "The Tight Spot": "Step out in style with The Tight Spot, your specialist for luxury legwear. featuring an unrivaled selection of hosiery from the world's top brands, they help you find the perfect tights, stockings, and leggings to complete any outfit with confidence.",
    "Thrifty Rent-A-Car System, Inc.": "Spend less, do more with Thrifty Car Rental, the brand for savvy travelers. offering great cars at great rates, Thrifty makes it easy to get behind the wheel and explore your destination without blowing your travel budget.",
    "TideWe": "Embrace the outdoors with TideWe, your partner for hunting and fishing gear. specialized in affordable, high-quality waders and boots, TideWe equips you to face the elements comfortably, so you can focus on the thrill of the pursuit.",
    "Troy Bilt": "Master your yard with Troy-Bilt, the rugged outdoor power equipment brand. built to last and easy to use, their mowers, tillers, and snow blowers help you tackle your yard work with confidence and pride, season after season.",
    "Try The World": "Taste the globe with Try The World, the gourmet subscription box for foodies. Curating authentic snacks and ingredients from a different country every month, they invite you on a culinary journey that brings international culture right to your kitchen.",
    "Tsarbomba": "Make a statement with Tsarbomba, the watch brand that defies convention. inspired by mechanical engineering and bold aesthetics, Tsarbomba creates avant-garde timepieces that are robust, eye-catching, and unapologetically unique.",
    "UGears": "Build your imagination with UGears, the creators of exquisite mechanical wooden models. interlocking without glue or batteries, these intricate 3D puzzles come to life with motion, offering a rewarding DIY experience that results in a stunning work of art.",
    "UNice": "Unleash your beauty with UNice, a global leader in human hair products. obsessed with quality and style, UNice offers an endless variety of premium wigs and weaves, empowering women to experiment with their look and express their true selves.",
    "UNIONBAY": "Live authentically with UNIONBAY, a leading lifestyle brand for the youth. rooted in sportswear and denim, UNIONBAY offers laid-back, cool, and affordable clothing that embodies the spirit of freedom and individuality.",
    "Verb Products": "Good hair is easy with Verb, the haircare brand that bridges the gap between drugstore and high-end. offering professional-quality products at an accessible price, Verb keeps it simple: no parabens, no gluten, no harmful sulfates, just great hair.",
    "Verification Advertiser": "Validation implies trust, and Verification Advertiser acts as the benchmark for system integrity. Ensuring processes run smoothly and data aligns perfectly, this entity stands as the silent guardian of accuracy within the network.",
    "Villeroy & Boch": "Elevate your home with Villeroy & Boch, a symbol of timeless elegance since 1748. renowned for premium porcelain and ceramics, their dining and bathroom collections blend tradition with innovative design, adding a touch of luxury to everyday living.",
    "VoIP Supply": "Connect with clarity using VoIP Supply, North America's leading VoIP solutions provider. delivering friendly expertise and a vast selection of hardware and services, they help businesses build reliable, efficient communication systems that drive success.",
    "WebEyeCare": "See savings with WebEyeCare, your reliable source for contact lenses and glasses. committed to lowest prices and fast shipping, they make it hassle-free to order your prescription eyewear online, keeping your vision sharp and your wallet happy.",
    "Whirlpool USA": "Care for your family with Whirlpool, the world's leading kitchen and laundry appliance brand. designed with purposeful innovation, Whirlpool appliances sense and adapt to your needs, helping you manage your home with care and efficiency every day.",
    "ZEAL PET": "Feed them love with ZEAL PET, the natural choice for pet nutrition. sourcing premium ingredients from New Zealand, ZEAL offers air-dried treats and food that are pure, tasty, and packed with the goodness your pets need to thrive.",
    "Zlike Hair": "Glam up with Zlike Hair, your destination for premium quality hair extensions. focusing on natural texture and longevity, Zlike provides versatile hair solutions that give you the volume, length, and confidence to rock any style you desire."
};

async function updateBrands() {
    const batch = db.batch();
    let count = 0;

    // Iterate through pre-defined descriptions
    for (const [name, desc] of Object.entries(descriptions)) {
        // Query for brand by name
        // Note: In a real scenario with 1000s, querying one by one is slow.
        // But for ~100 in a script, it's acceptable.

        // We need to match potentially imprecise names if IDs aren't used.
        // But the list provided names that look like exact matches from a previous dump.

        const snapshot = await db.collection('advertisers').where('name', '==', name).get();

        if (snapshot.empty) {
            console.log(`Skipping ${name}: Not found in DB.`);
            continue;
        }

        // There might be duplicates across networks (Rakuten-ID, CJ-ID).
        // The user wants to update the brands "listed in /mission-control".
        // The /mission-control page lists ALL matches.
        // We should update ALL docs with this name.

        snapshot.forEach(doc => {
            batch.update(doc.ref, { manualDescription: desc });
            count++;
        });
    }

    if (count > 0) {
        await batch.commit();
        console.log(`Successfully updated descriptions for ${count} advertiser documents.`);
    } else {
        console.log('No updates performed.');
    }
}

updateBrands();
